export { default as Hero } from "./Hero";
export { default as Skills } from "./Skills";
export { default as Service } from "./Services";
export { default as Projects } from "./Projects";
export { default as Testimonials } from "./Testimonials";
export { default as HireMe } from "./HireMe";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as Navbar } from "./Navbar";